Minor modifications to get a clean build under VS2005
Some symbols should be marked as PRIVATE as per help for Linker Tools
Warning LNK4104.

menu.c complained about implicit declaration of sprintf and about C++
way of declaring variables (error C2143 & co.)

Neither of these changes are required for gcc, even though with -Wall and
-std=c99 similar warnings are produced.